name: Deploy to Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --unhandled-rejections=strict

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Publish to Production
        run: curl -X POST "$DEPLOY_HOOK"
        env:
          DEPLOY_HOOK: ${{ secrets.PRODUCTION_DEPLOY_HOOK }}
